name: Release

# 验证是否正确，先使用PR 的触发条件
#on:
#  push:
#    branches:
#      - main
#      - master
#    tags:
#      - "v*.*.*"
on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

# 定义环境变量
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  # 任务 1: 检查 Git Tag 和 package.json 的版本是否一致
  get_version:
    name: Check Release Tag and package.json Version Consistency
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get version from package.json
        id: get_version
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          echo "Current tag: $TAG_REF"
          PKG_VERSION=$(jq -r .version package.json)
          echo "package.json version: $PKG_VERSION"
          echo "version=$PKG_VERSION" >> $GITHUB_OUTPUT
          if [[ "$TAG_REF" != "v$PKG_VERSION" ]]; then
            echo "Tag ($TAG_REF) does not match package.json version (v$PKG_VERSION)."
            exit 0
          fi
          echo "Tag and package.json version are consistent."

  # 任务 2: 为 Windows, macOS, Linux, 和 Android 构建和发布
  build-artifacts:
    name: Build and Release
    needs: [get_version]
    strategy:
      fail-fast: false
      matrix:
        # 定义需要构建的平台和架构
        include:
          # Windows
          - os: windows-latest
            platform: windows
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - os: windows-latest
            platform: windows
            target: aarch64-pc-windows-msvc
            arch: aarch64
          # macOS
          - os: macos-latest
            platform: macos
            target: aarch64-apple-darwin
            arch: aarch64
          - os: macos-latest
            platform: macos
            target: x86_64-apple-darwin
            arch: x86_64
          # Linux
          - os: ubuntu-22.04
            platform: linux
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu-22.04
            platform: linux
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          # Android
          - os: ubuntu-22.04
            platform: android
            target: x86_64-linux-android
            arch: x86_64
          - os: ubuntu-22.04
            platform: android
            target: aarch64-linux-android
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 安装 Rust Stable
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 下载并配置 Android SDK/NDK
      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 26.1.10909125

      - name: Install NDK
        if: matrix.platform == 'android'
        run: sdkmanager "ndk;26.1.10909125"

      # 添加 Rust 编译目标
      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      # Rust 缓存
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      # 仅在 Ubuntu 上安装依赖
      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libgtk-3-dev libssl-dev xdg-utils librsvg2-dev libappindicator3-dev  patchelf

      - name: Download and setup eCapture for ${{ matrix.arch }}
        shell: bash
        if: matrix.platform == 'linux' || matrix.platform == 'android'
        run: |
          if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
            ECAPTURE_ARCH="amd64"
          else
            ECAPTURE_ARCH="arm64"
          fi
          pwd
          ECAPTURE_LATEST=$(curl -s https://api.github.com/repos/gojue/ecapture/releases/latest | grep tag_name | cut -d '"' -f 4)
          if [[ $? -ne 0 ]]; then
            echo "Failed to fetch the latest release."
            exit 1
          fi

          ECAPTURE_TAR="ecapture-${ECAPTURE_LATEST}-${{ matrix.platform }}-${ECAPTURE_ARCH}.tar.gz"
          ECAPTURE_DIR="ecapture-${ECAPTURE_LATEST}-${{ matrix.platform }}-${ECAPTURE_ARCH}"

          wget "https://github.com/gojue/ecapture/releases/download/${ECAPTURE_LATEST}/${ECAPTURE_TAR}" || { echo "Download failed"; exit 1; }
          tar -zxvf "${ECAPTURE_TAR}" || { echo "Extract failed"; exit 1; }

          mkdir -p src-tauri/binaries
          cp "${ECAPTURE_DIR}/ecapture" src-tauri/binaries/${{ matrix.platform }}_ecapture_${ECAPTURE_ARCH} || { echo "Copy failed"; exit 1; }
          ls src-tauri/binaries/

      # 设置 Node.js 环境
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 设置 pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest

      # 安装前端依赖
      - name: Pnpm install
        run: |
          pnpm i

      - name: Create keystore.properties for Android signing
        if: matrix.platform == 'android'
        run: |
          # 动态创建 src-tauri/gen/android 目录（如果不存在）
          pwd
          pnpm tauri android init
          mkdir -p src-tauri/gen/android

          # 将 Base64 编码的密钥文件解码，并保存到 Runner 的临时目录
          echo "${{ secrets.ANDROID_SIGNING_RELEASE_KEY }}" | base64 --decode > src-tauri/gen/android/release.decrypted.jks

          # 将签名信息写入 keystore.properties 文件
          cat <<EOF > src-tauri/gen/android/keystore.properties
          password=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS }}
          storeFile=${{ github.workspace }}/src-tauri/gen/android/release.decrypted.jks
          keyPassword=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS_PASSWORD }}
          EOF
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125


      - name: eCaptureQ build (non-Android)
        if: matrix.platform != 'android'
        uses: tauri-apps/tauri-action@v0.5.22
        env:
          DECOUPLED_MODE: true
          RUST_TARGET: ${{ matrix.target }}
          NODE_OPTIONS: "--max_old_space_size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY_PASSWORD }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: v${{ steps.get_version.outputs.version }}
          appName: eCaptureQ
          appVersion: ${{ steps.get_version.outputs.version }}
          releaseName: "eCaptureQ v${{ steps.get_version.outputs.version }}"
          releaseBody: ""
          releaseDraft: true
          prerelease: 'false'

      - name: eCaptureQ build (Android) ${{ matrix.arch }}
        if: matrix.platform == 'android'
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125
        run: |
          pnpm tauri android build --target ${{ matrix.arch }}

      - name: Sign APK
        if: matrix.platform == 'android'
        env:
          ANDROID_SIGNING_RELEASE_KEY: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY }}
          ANDROID_SIGNING_RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS }}
          ANDROID_SIGNING_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY_PASSWORD }}
          ANDROID_SIGNING_RELEASE_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS_PASSWORD }}
        run: |
          ls -la src-tauri/gen/android/keystore.properties
          ls -la src-tauri/gen/android/your-keystore.jks
          ${{ env.ANDROID_HOME }}/build-tools/34.0.0/apksigner sign \
          --ks ${{ github.workspace }}/src-tauri/gen/android/release.decrypted.jks \
          --ks-key-alias env:ANDROID_SIGNING_RELEASE_KEY_ALIAS \
          --ks-pass env:ANDROID_SIGNING_RELEASE_KEY_PASSWORD \
          --key-pass env:ANDROID_SIGNING_RELEASE_KEY_ALIAS_PASSWORD \
          --v1-signing-enabled true \
          --v2-signing-enabled true \
          --v3-signing-enabled true \
          --verbose \
          --out "./src-tauri/gen/android/app/build/outputs/apk/universal/release/eCaprureQ_v${{ steps.get_version.outputs.version }}_${{ matrix.arch }}.apk" \
          src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

      - name: Publish
        if: matrix.platform == 'android'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: eCaptureQ v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: |
            ./src-tauri/gen/android/app/build/outputs/apk/universal/release/eCaptureQ_v${{ steps.get_version.outputs.version }}_${{ matrix.arch }}.apk