name: Release

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

permissions: write-all

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  get_version:
    name: Check Release Tag and package.json Version Consistency
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Get version from package.json
        id: get_version
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          echo "Current tag: $TAG_REF"
          PKG_VERSION=$(jq -r .version package.json)
          echo "package.json version: $PKG_VERSION"
          echo "version=$PKG_VERSION" >> $GITHUB_OUTPUT
          if [[ "$TAG_REF" != "v$PKG_VERSION" ]]; then
            echo "Tag ($TAG_REF) does not match package.json version (v$PKG_VERSION)."
            exit 0
          fi
          echo "Tag and package.json version are consistent."

  build-artifacts:
    name: Build and Release
    needs: [get_version]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: windows
            target: x86_64-pc-windows-msvc
            arch: x86_64
          - os: windows-latest
            platform: windows
            target: aarch64-pc-windows-msvc
            arch: aarch64
          - os: macos-latest
            platform: macos
            target: aarch64-apple-darwin
            arch: aarch64
          - os: macos-latest
            platform: macos
            target: x86_64-apple-darwin
            arch: x86_64
          - os: ubuntu-22.04
            platform: linux
            target: x86_64-unknown-linux-gnu
            arch: x86_64
          - os: ubuntu-22.04
            platform: linux
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: ubuntu-22.04
            platform: android
            target: x86_64-linux-android
            arch: x86_64
          - os: ubuntu-22.04
            platform: android
            target: aarch64-linux-android
            arch: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Java
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk-version: 26.1.10909125

      - name: Install NDK
        if: matrix.platform == 'android'
        run: sdkmanager "ndk;26.1.10909125"

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev libgtk-3-dev libssl-dev xdg-utils librsvg2-dev libappindicator3-dev patchelf

      - name: Download and setup eCapture for ${{ matrix.arch }}
        shell: bash
        if: matrix.platform == 'linux' || matrix.platform == 'android'
        run: |
          if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
            ECAPTURE_ARCH="amd64"
          else
            ECAPTURE_ARCH="arm64"
          fi
          
          ECAPTURE_PLATFORM="${{ matrix.platform }}"
          if [[ "${{ matrix.platform }}" == "android" ]]; then
            echo "Android platform detected. Using 'linux' binaries for eCapture."
            ECAPTURE_PLATFORM="linux"
          fi
          
          ECAPTURE_LATEST=$(curl -s https://api.github.com/repos/gojue/ecapture/releases/latest | grep tag_name | cut -d '"' -f 4)
          if [[ -z "$ECAPTURE_LATEST" ]]; then
            echo "Failed to fetch the latest eCapture release version."
            exit 1
          fi

          ECAPTURE_TAR="ecapture-${ECAPTURE_LATEST}-${ECAPTURE_PLATFORM}-${ECAPTURE_ARCH}.tar.gz"
          ECAPTURE_DIR="ecapture-${ECAPTURE_LATEST}-${ECAPTURE_PLATFORM}-${ECAPTURE_ARCH}"

          wget "https://github.com/gojue/ecapture/releases/download/${ECAPTURE_LATEST}/${ECAPTURE_TAR}" || { echo "Download failed"; exit 1; }
          tar -zxvf "${ECAPTURE_TAR}" || { echo "Extract failed"; exit 1; }
          mkdir -p src-tauri/binaries
          
          SOURCE_FILE="${ECAPTURE_DIR}/ecapture"
          DEST_FILE="src-tauri/binaries/${{ matrix.platform }}_ecapture_${ECAPTURE_ARCH}"
          
          cp "${SOURCE_FILE}" "${DEST_FILE}" || { echo "Copy failed"; exit 1; }
          ls src-tauri/binaries/

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest

      - name: Pnpm install
        run: pnpm i

      - name: Create keystore.properties for Android signing
        if: matrix.platform == 'android'
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125 # <-- 这里采纳了您范例中的正确设置
        run: |
          pnpm tauri android init
          echo "${{ secrets.ANDROID_SIGNING_RELEASE_KEY }}" | base64 --decode > release.decrypted.jks
          mkdir -p src-tauri/gen/android
          cat <<EOF > src-tauri/gen/android/keystore.properties
          password=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS }}
          storeFile=${{ github.workspace }}/release.decrypted.jks
          keyPassword=${{ secrets.ANDROID_SIGNING_RELEASE_KEY_ALIAS_PASSWORD }}
          EOF

      - name: Build Desktop Artifacts (Windows/macOS/Linux)
        if: matrix.platform != 'android'
        run: pnpm tauri build

      - name: Build Android Artifact
        if: matrix.platform == 'android'
        env:
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/26.1.10909125
        run: |
          pnpm tauri android build --target ${{ matrix.arch }}

      - name: Rename Android Artifact
        if: matrix.platform == 'android'
        run: |
          mv src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk ./eCaptureQ_v${{ needs.get_version.outputs.version }}_${{ matrix.arch }}.apk

      - name: Publish Desktop Artifacts
        if: matrix.platform != 'android'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: eCaptureQ v${{ needs.get_version.outputs.version }}
          tag_name: v${{ needs.get_version.outputs.version }}
          generate_release_notes: true
          files: |
            src-tauri/target/release/bundle/msi/eCaptureQ_*.msi
            src-tauri/target/release/bundle/nsis/eCaptureQ_*-setup.exe
            src-tauri/target/release/bundle/dmg/eCaptureQ_*.dmg
            src-tauri/target/release/bundle/appimage/eCaptureQ_*.AppImage

      - name: Publish Android Artifact
        if: matrix.platform == 'android'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: eCaptureQ v${{ needs.get_version.outputs.version }}
          tag_name: v${{ needs.get_version.outputs.version }}
          generate_release_notes: true
          files: ./eCaptureQ_v${{ needs.get_version.outputs.version }}_${{ matrix.arch }}.apk